export const STARTER_PUBLIC_TRIAL_DAYS = 14;
export const STARTER_PUBLIC_PRICE_EUR = 199;
export const STARTER_PUBLIC_BILLING_CYCLE_LABEL = "pro 4 Wochen";
export const STARTER_PUBLIC_PLAN_NAME = "Advaic Starter";

export const STARTER_PUBLIC_PRICE_LABEL = `${STARTER_PUBLIC_PRICE_EUR} € ${STARTER_PUBLIC_BILLING_CYCLE_LABEL}`;
export const STARTER_PUBLIC_TRIAL_LABEL = `${STARTER_PUBLIC_TRIAL_DAYS} Tage Testphase`;
export const STARTER_PUBLIC_TRIAL_AND_PRICE_LABEL = `${STARTER_PUBLIC_TRIAL_LABEL}, danach ${STARTER_PUBLIC_PRICE_LABEL}`;
