-- Seed: gezielte Makler-Prospects (kleine Agenturen / Solo-Makler)
-- Datum: 2026-03-04
-- Scope: nur fuer Agent-ID 3582c768-0edd-4536-9501-268b881599df
-- Quellen: oeffentlich sichtbare Profil- und Impressumsdaten (v. a. ImmoScout24 + Firmenwebseiten)

begin;

with cfg as (
  select '3582c768-0edd-4536-9501-268b881599df'::uuid as agent_id
),
seed as (
  select *
  from (
    values
      (
        'PAPE-IMMO Benjamin Pape',
        'Benjamin Pape',
        'info@pape-immo.de',
        'Inhaber',
        'Salzgitter',
        'Niedersachsen',
        'https://www.pape-immo.de',
        'https://www.immobilienscout24.de/anbieter/profil/benjamin-pape-65947979',
        3,
        100,
        0,
        'kauf',
        'Kleines Inhaber-Buero mit klarer Kauf-Ausrichtung',
        'Wenig Teamkapazitaet, aber hohe Erwartung an schnelle, persoenliche Erstreaktion',
        'Im Profil sind 3 aktive Inserate sichtbar, 100 Prozent Kauf. Ideal fuer sicheren Autopilot bei Standardanfragen.',
        90,
        'A',
        'email'
      ),
      (
        'Dreher Immobilien',
        'Mirko Dreher',
        'info@dreher-immobilien.de',
        'Inhaber',
        'Bad Nauheim',
        'Hessen',
        'https://www.dreher-immobilien.de',
        'https://www.immobilienscout24.de/anbieter/profil/dreher-immobilien-214197',
        8,
        13,
        87,
        'miete',
        'Kleiner regionaler Makler mit starker Vermietungsquote',
        'Viele wiederkehrende Miet-Anfragen (Verfuegbarkeit, Besichtigung, Unterlagen) kosten Zeit',
        '8 aktive Inserate mit 87 Prozent Miete. Schnelle, konsistente Antworten bringen hier direkt Entlastung.',
        92,
        'A',
        'email'
      ),
      (
        'Mosler Immobilien',
        'Dirk Mosler',
        'info@mosler.immo',
        'Inhaber',
        'Remscheid',
        'Nordrhein-Westfalen',
        'https://mosler.immo',
        'https://www.immobilienscout24.de/anbieter/profil/dirk-mosler-105652',
        5,
        100,
        0,
        'kauf',
        'Lokales Inhaberbuero mit ueberschaubarem Kauf-Portfolio',
        'Jede Anfrage ist wichtig; unklare Mails duerfen nicht automatisch falsch beantwortet werden',
        '5 aktive Inserate, voll auf Kauf. Gute Passung fuer Guardrails + Freigabe bei Sonderfaellen.',
        88,
        'A',
        'email'
      ),
      (
        'Merz Immobilien',
        'Gunter Merz',
        null,
        'Inhaber',
        'Karlsruhe',
        'Baden-Wuerttemberg',
        'https://www.immobilienscout24.de/anbieter/profil/gunter-merz-174789',
        'https://www.immobilienscout24.de/anbieter/profil/gunter-merz-174789',
        11,
        36,
        64,
        'gemischt',
        'Kleine Agentur mit gemischtem Bestand, Schwerpunkt Miete',
        'Gemischte Pipeline erhoeht Entscheidungsaufwand (Auto vs. Freigabe)',
        '11 Inserate, davon 64 Prozent Miete. Gemischte Anfragen sind ideal fuer klare Routing-Regeln.',
        84,
        'A',
        'kontaktformular'
      ),
      (
        'Blancke Immobilien',
        'Selma Blancke',
        'info@blancke-immobilien.de',
        'Inhaberin',
        'Bayreuth',
        'Bayern',
        'https://www.blancke-immobilien.de',
        'https://www.immobilienscout24.de/anbieter/profil/selma-blancke-70505745',
        4,
        50,
        50,
        'gemischt',
        'Inhabergefuehrte Boutique-Struktur mit gemischtem Objektmix',
        'Hohe Anspruchshaltung an Ton und Seriositaet bei kleinem Team',
        '4 aktive Inserate mit 50/50 Mix. Personalisierter Stil + QA-Checks sind hier zentral.',
        86,
        'A',
        'email'
      ),
      (
        'NOVO Immobilien',
        'Ingolf Schmidt',
        null,
        'Inhaber',
        'Neetze',
        'Niedersachsen',
        'https://www.immobilienscout24.de/anbieter/profil/ingolf-schmidt-83092017',
        'https://www.immobilienscout24.de/anbieter/profil/ingolf-schmidt-83092017',
        4,
        75,
        25,
        'kauf',
        'Kleinstruktur mit deutlichem Kauf-Fokus',
        'Bei kleinen Teams ist Reaktionsgeschwindigkeit oft vom Tagesgeschaeft abhaengig',
        '4 Inserate, 75 Prozent Kauf. Klarer Use-Case fuer sicheren Autopilot bei Standardfragen.',
        85,
        'A',
        'kontaktformular'
      ),
      (
        'Haus&Geld Immobilien',
        'Monika Turlej',
        null,
        'Inhaberin',
        'Montabaur',
        'Rheinland-Pfalz',
        'https://www.immobilienscout24.de/anbieter/profil/monika-turlej-1096658',
        'https://www.immobilienscout24.de/anbieter/profil/monika-turlej-1096658',
        4,
        100,
        0,
        'kauf',
        'Inhabergefuehrtes Maklerprofil mit Kauf-Schwerpunkt',
        'Wenige, aber wertige Anfragen erfordern sehr sauberen Ton und nachvollziehbaren Verlauf',
        '4 aktive Kauf-Inserate. Vertrauensthema: nur auto senden, wenn der Fall eindeutig ist.',
        84,
        'A',
        'kontaktformular'
      ),
      (
        'Kutsche Finanz Immobilien',
        'Annika Pordzik',
        null,
        'Ansprechpartnerin',
        'Geseke',
        'Nordrhein-Westfalen',
        'https://www.immobilienscout24.de/anbieter/profil/annika-pordzik-86514895',
        'https://www.immobilienscout24.de/anbieter/profil/annika-pordzik-86514895',
        4,
        50,
        50,
        'gemischt',
        'Kleine Einheit mit gemischter Nachfrage',
        'Gemischte Faelle und Finanzierungsfragen erhoehen das Risiko fuer unpassende Standardantworten',
        '4 Inserate mit 50/50 Mix. Gute Passung fuer Freigabe-Logik bei unklaren Faellen.',
        80,
        'B',
        'kontaktformular'
      ),
      (
        'Elevaa Hausverwaltung & Immobilien',
        'Oguz Dogan',
        'hallo@elevaa.de',
        'Inhaber',
        'Backnang',
        'Baden-Wuerttemberg',
        'https://elevaa.de',
        'https://www.immobilienscout24.de/anbieter/profil/oguz-dogan-79627870',
        5,
        80,
        20,
        'kauf',
        'Kleine Agentur mit Kauf-Schwerpunkt und klarer lokaler Sichtbarkeit',
        'Mehrere Eingangskanaele erzeugen manuellen Sortieraufwand im Postfach',
        '5 Inserate, 80 Prozent Kauf. Advaic kann Standardanfragen schnell vorsortieren und sicher beantworten.',
        87,
        'A',
        'email'
      ),
      (
        'Roemer & Partner',
        'Jasmin Karaman',
        null,
        'Ansprechpartnerin',
        'Marl',
        'Nordrhein-Westfalen',
        'https://www.immobilienscout24.de/anbieter/profil/jasmin-karaman-86627435',
        'https://www.immobilienscout24.de/anbieter/profil/jasmin-karaman-86627435',
        5,
        20,
        80,
        'miete',
        'Kleine Agentur mit deutlichem Vermietungs-Fokus',
        'Hohe Wiederholung bei Vermietungsanfragen bindet Zeit im Tagesgeschaeft',
        '5 Inserate, 80 Prozent Miete. Sehr guter Fit fuer standardisierte Erstantworten mit Guardrails.',
        90,
        'A',
        'kontaktformular'
      ),
      (
        'V.I.S. Vermoegensverwaltung Immobilien Service',
        'Thomas Neuhoff',
        null,
        'Inhaber',
        'Regensburg',
        'Bayern',
        'https://www.immobilienscout24.de/anbieter/profil/thomas-neuhoff-81294142',
        'https://www.immobilienscout24.de/anbieter/profil/thomas-neuhoff-81294142',
        3,
        0,
        100,
        'miete',
        'Kleine, vermietungsnahe Struktur mit klarem Fokus',
        'Bei reinem Mietfokus treten viele aehnliche Fragen in kurzer Zeit auf',
        '3 Inserate und 100 Prozent Miete. Passend fuer schnellen Auto-Versand bei klaren Standardfaellen.',
        89,
        'A',
        'kontaktformular'
      ),
      (
        'Cornelis Verwaltungs- und Immobilienmanagement',
        'Mike Cornelis',
        null,
        'Inhaber',
        'Gelsenkirchen',
        'Nordrhein-Westfalen',
        'https://www.immobilienscout24.de/anbieter/profil/mike-cornelis-75635850',
        'https://www.immobilienscout24.de/anbieter/profil/mike-cornelis-75635850',
        3,
        100,
        0,
        'kauf',
        'Kleine Einheit mit Kauf-Fokus',
        'Kleine Teams brauchen kurze, konsistente Antworten ohne Qualitaetsverlust',
        '3 Inserate, komplett Kauf. Klarer Kandidat fuer vorsichtig gestarteten Autopilot.',
        85,
        'A',
        'kontaktformular'
      ),
      (
        'BGR Immobilien',
        'Claus Braunen',
        null,
        'Inhaber',
        'Viersen',
        'Nordrhein-Westfalen',
        'https://www.immobilienscout24.de/anbieter/profil/claus-braunen-73256998',
        'https://www.immobilienscout24.de/anbieter/profil/claus-braunen-73256998',
        5,
        100,
        0,
        'kauf',
        'Kleiner Kauf-Spezialist',
        'Im Verkaufsfokus muss Ton professionell bleiben, auch bei hoher Last',
        '5 Inserate mit 100 Prozent Kauf. Gute Passung fuer Stilvorgaben + Recheck vor Versand.',
        86,
        'A',
        'kontaktformular'
      ),
      (
        'BLI Group',
        'Moritz Pese',
        null,
        'Ansprechpartner',
        'Eching',
        'Bayern',
        'https://www.immobilienscout24.de/anbieter/profil/moritz-pese-83696884',
        'https://www.immobilienscout24.de/anbieter/profil/moritz-pese-83696884',
        5,
        20,
        80,
        'miete',
        'Kleine Agentur mit hohem Mietanteil',
        'Wiederkehrende Vermietungsfragen eignen sich stark fuer teilautomatisierte Antworten',
        '5 Inserate, 80 Prozent Miete. Relevanz hoch fuer Auto/Freigabe-Split.',
        88,
        'A',
        'kontaktformular'
      ),
      (
        'Laage Immobilien',
        'Yvonne Laage',
        'anfragen@laage.immo',
        'Inhaberin',
        'Apensen',
        'Niedersachsen',
        'https://laage.immo',
        'https://www.immobilienscout24.de/anbieter/profil/yvonne-laage-76666068',
        5,
        100,
        0,
        'kauf',
        'Inhabergefuehrte Boutique mit klarem Kaufportfolio',
        'Kleine Teams brauchen saubere Priorisierung statt Inbox-Ueberlastung',
        '5 Inserate, 100 Prozent Kauf. Sehr gut fuer vorsichtigen Autopilot mit Freigabe-Fallback.',
        87,
        'A',
        'email'
      ),
      (
        'Partaw Investa',
        'Sohrab Partaw',
        null,
        'Inhaber',
        'Wiesbaden',
        'Hessen',
        'https://www.immobilienscout24.de/anbieter/profil/sohrab-partaw-86795173',
        'https://www.immobilienscout24.de/anbieter/profil/sohrab-partaw-86795173',
        2,
        0,
        100,
        'miete',
        'Sehr kleine Einheit, klarer Mietfokus',
        'Schon wenige parallele Anfragen koennen den Antwort-Flow bremsen',
        '2 Inserate, 100 Prozent Miete. Minimal-Setup mit viel Freigabe eignet sich fuer Pilotstart.',
        82,
        'B',
        'kontaktformular'
      ),
      (
        'Jacobs Immobilien',
        'Stefan Jacobs',
        'info@jacobsimmobilien.com',
        'Inhaber',
        'Wunstorf',
        'Niedersachsen',
        'https://www.jacobsimmobilien.com',
        'https://www.immobilienscout24.de/anbieter/profil/stefan-jacobs-71192420',
        6,
        100,
        0,
        'kauf',
        'Kleine Inhaberagentur mit Kauf-Spezialisierung',
        'Bei Kaufanfragen sind klare naechste Schritte entscheidend fuer Conversion',
        '6 Inserate, 100 Prozent Kauf. Gute Passung fuer strukturierte Antwortbausteine.',
        88,
        'A',
        'email'
      ),
      (
        'Estaetes Lanzilotto',
        'Daniela Lanzilotto',
        null,
        'Inhaberin',
        'Juelich',
        'Nordrhein-Westfalen',
        'https://www.immobilienscout24.de/anbieter/profil/daniela-lanzilotto-69362548',
        'https://www.immobilienscout24.de/anbieter/profil/daniela-lanzilotto-69362548',
        5,
        80,
        20,
        'kauf',
        'Kleine Agentur mit starkem Kaufanteil',
        'Konstante Erreichbarkeit ist bei kleiner Teamgroesse schwer sicherzustellen',
        '5 Inserate, 80 Prozent Kauf. Pilot mit sicheren Guardrails passt gut.',
        85,
        'A',
        'kontaktformular'
      ),
      (
        'Thomas Ulhas Immobilien',
        'Thomas Ulhas',
        null,
        'Inhaber',
        'Plaidt',
        'Rheinland-Pfalz',
        'https://www.immobilienscout24.de/anbieter/profil/thomas-ulhas-76758495',
        'https://www.immobilienscout24.de/anbieter/profil/thomas-ulhas-76758495',
        8,
        88,
        12,
        'kauf',
        'Kleine bis mittlere regionale Einheit mit Kauflast',
        'Mehrere gleichartige Anfragen koennen Antwortzeiten verlaengern',
        '8 Inserate, 88 Prozent Kauf. Hoher Fit fuer standardisierte Erstreaktionen.',
        84,
        'A',
        'kontaktformular'
      ),
      (
        'Immobilienservice Zimmermann',
        'Uwe Zimmermann',
        null,
        'Inhaber',
        'Achern',
        'Baden-Wuerttemberg',
        'https://www.immobilienscout24.de/anbieter/profil/uwe-zimmermann-67748417',
        'https://www.immobilienscout24.de/anbieter/profil/uwe-zimmermann-67748417',
        7,
        86,
        14,
        'kauf',
        'Kleine regionale Agentur mit starkem Kaufanteil',
        'Bei kleinem Team bleibt haeufig wenig Zeit fuer saubere Follow-up-Steuerung',
        '7 Inserate, 86 Prozent Kauf. Interessant fuer Pilot mit Fokus auf Antwortgeschwindigkeit.',
        83,
        'B',
        'kontaktformular'
      ),
      (
        'IHR-Immobilien',
        'Herbert Resch',
        null,
        'Inhaber',
        'Bodenmais',
        'Bayern',
        'https://www.immobilienscout24.de/anbieter/profil/herbert-resch-245850',
        'https://www.immobilienscout24.de/anbieter/profil/herbert-resch-245850',
        8,
        100,
        0,
        'kauf',
        'Regionale Inhaberagentur mit durchgaengigem Kauffokus',
        'Schnelle Reaktion auf Erstanfragen entscheidet stark ueber Terminquote',
        '8 Inserate, 100 Prozent Kauf. Sehr guter Fit fuer kontrollierten Autopilot.',
        86,
        'A',
        'kontaktformular'
      ),
      (
        'EK-Immobilien',
        'Elisabeth Krell',
        null,
        'Inhaberin',
        'Vaterstetten',
        'Bayern',
        'https://www.immobilienscout24.de/anbieter/profil/elisabeth-krell-156360',
        'https://www.immobilienscout24.de/anbieter/profil/elisabeth-krell-156360',
        23,
        17,
        83,
        'miete',
        'Etabliertes regionales Buero mit starkem Vermietungsanteil',
        'Hoeheres Anfragevolumen in der Vermietung erzeugt hohen Inbox-Druck',
        '23 Inserate mit 83 Prozent Miete. Hohe Entlastungswirkung durch automatisierte Standardantworten.',
        79,
        'B',
        'kontaktformular'
      )
  ) as t(
    company_name,
    contact_name,
    contact_email,
    contact_role,
    city,
    region,
    website_url,
    source_url,
    active_listings_count,
    share_kauf_percent,
    share_miete_percent,
    object_focus,
    target_group,
    pain_point_hypothesis,
    personalization_hook,
    fit_score,
    priority,
    preferred_channel
  )
),
upserted as (
  insert into public.crm_prospects (
    agent_id,
    company_name,
    contact_name,
    contact_email,
    contact_role,
    city,
    region,
    website_url,
    source_url,
    source_checked_at,
    linkedin_url,
    linkedin_search_url,
    linkedin_relevance_note,
    object_focus,
    active_listings_count,
    share_miete_percent,
    share_kauf_percent,
    object_types,
    target_group,
    process_hint,
    primary_objection,
    primary_pain_hypothesis,
    secondary_pain_hypothesis,
    automation_readiness,
    cta_preference_guess,
    personalization_evidence,
    hypothesis_confidence,
    owner_led,
    brand_tone,
    trust_signals,
    pain_point_hypothesis,
    personalization_hook,
    fit_score,
    priority,
    preferred_channel,
    next_action,
    next_action_at,
    tags,
    metadata
  )
  select
    cfg.agent_id,
    s.company_name,
    s.contact_name,
    lower(s.contact_email),
    s.contact_role,
    s.city,
    s.region,
    s.website_url,
    s.source_url,
    '2026-03-04'::date,
    case
      when s.company_name = 'Mosler Immobilien' then 'https://de.linkedin.com/company/dirk-mosler-immobilien'
      else null
    end,
    format(
      'https://www.linkedin.com/search/results/all/?keywords=%s',
      replace(concat_ws(' ', s.contact_name, s.company_name, s.city, 'Immobilienmakler'), ' ', '%20')
    ),
    case
      when s.company_name = 'Mosler Immobilien'
        then 'LinkedIn-Firmenseite gefunden. Sichtbares Posting im PropCon/BVFI-Kontext (Makler-Automatisierung).'
      else null
    end,
    s.object_focus,
    s.active_listings_count,
    s.share_miete_percent,
    s.share_kauf_percent,
    case
      when s.object_focus = 'miete' then array['Wohnung', 'Miete']::text[]
      when s.object_focus = 'kauf' then array['Wohnung', 'Haus']::text[]
      else array['Wohnung', 'Haus', 'Gemischt']::text[]
    end,
    s.target_group,
    format(
      'ImmoScout24-Profil aktiv: %s Inserate (%s%% Kauf / %s%% Miete).',
      s.active_listings_count,
      s.share_kauf_percent,
      s.share_miete_percent
    ),
    'Kontrollverlust bei Auto-Antworten',
    s.pain_point_hypothesis,
    'Unsichere Sonderfälle sollten immer in die Freigabe gehen.',
    case
      when s.fit_score >= 86 then 'hoch'
      when s.fit_score >= 80 then 'mittel'
      else 'niedrig'
    end,
    case
      when s.preferred_channel = 'email' then 'kurze_mail_antwort'
      when s.preferred_channel = 'kontaktformular' then 'formular_antwort'
      else '15_min_call'
    end,
    format(
      'Beleg: %s Inserate mit Mix %s%% Kauf / %s%% Miete (Quelle: %s).',
      s.active_listings_count,
      s.share_kauf_percent,
      s.share_miete_percent,
      s.source_url
    ),
    0.82,
    (s.contact_role in ('Inhaber', 'Inhaberin')),
    'professionell',
    case
      when s.company_name = 'Mosler Immobilien' then array['LinkedIn-Aktivitaet (PropCon/BVFI Kontext)']::text[]
      else '{}'::text[]
    end,
    s.pain_point_hypothesis,
    s.personalization_hook,
    s.fit_score,
    s.priority,
    s.preferred_channel,
    'Tester-Einladung personalisieren und ohne Kaufdruck senden',
    now() + interval '1 day',
    array['pilot_target', 'small_agency', '2026_q1']::text[],
    jsonb_build_object(
      'research_date', '2026-03-04',
      'source_portal', 'immobilienscout24',
      'source_url', s.source_url,
      'active_listings_count', s.active_listings_count,
      'share_kauf_percent', s.share_kauf_percent,
      'share_miete_percent', s.share_miete_percent,
      'online_presence', jsonb_build_object(
        'immoscout_profile', true,
        'own_website_known', (s.website_url not like 'https://www.immobilienscout24.de/%'),
        'channel_preference', s.preferred_channel
      ),
      'advaic_relevance', case
        when s.fit_score >= 86 then 'hoch'
        when s.fit_score >= 80 then 'mittel_hoch'
        else 'mittel'
      end
    )
  from seed s
  cross join cfg
  on conflict (agent_id, lower(company_name), coalesce(lower(city), ''))
  do update set
    contact_name = excluded.contact_name,
    contact_email = excluded.contact_email,
    contact_role = excluded.contact_role,
    region = excluded.region,
    website_url = excluded.website_url,
    source_url = excluded.source_url,
    source_checked_at = excluded.source_checked_at,
    linkedin_url = excluded.linkedin_url,
    linkedin_search_url = excluded.linkedin_search_url,
    linkedin_relevance_note = excluded.linkedin_relevance_note,
    object_focus = excluded.object_focus,
    active_listings_count = excluded.active_listings_count,
    share_miete_percent = excluded.share_miete_percent,
    share_kauf_percent = excluded.share_kauf_percent,
    object_types = excluded.object_types,
    target_group = excluded.target_group,
    process_hint = excluded.process_hint,
    primary_objection = excluded.primary_objection,
    primary_pain_hypothesis = excluded.primary_pain_hypothesis,
    secondary_pain_hypothesis = excluded.secondary_pain_hypothesis,
    automation_readiness = excluded.automation_readiness,
    cta_preference_guess = excluded.cta_preference_guess,
    personalization_evidence = excluded.personalization_evidence,
    hypothesis_confidence = excluded.hypothesis_confidence,
    owner_led = excluded.owner_led,
    brand_tone = excluded.brand_tone,
    trust_signals = excluded.trust_signals,
    pain_point_hypothesis = excluded.pain_point_hypothesis,
    personalization_hook = excluded.personalization_hook,
    fit_score = excluded.fit_score,
    priority = excluded.priority,
    preferred_channel = excluded.preferred_channel,
    next_action = excluded.next_action,
    next_action_at = excluded.next_action_at,
    tags = excluded.tags,
    metadata = excluded.metadata,
    updated_at = now()
  returning id, agent_id, company_name, city
)
insert into public.crm_research_notes (
  prospect_id,
  agent_id,
  source_type,
  source_url,
  note,
  confidence,
  is_key_insight,
  metadata
)
select
  u.id,
  u.agent_id,
  'portal',
  s.source_url,
  format(
    'Scout-Signal: %s aktive Inserate, %s%% Kauf / %s%% Miete. Einordnung: %s.',
    s.active_listings_count,
    s.share_kauf_percent,
    s.share_miete_percent,
    case
      when s.object_focus = 'miete' then 'Vermietungsfokus'
      when s.object_focus = 'kauf' then 'Kauffokus'
      else 'gemischter Fokus'
    end
  ),
  0.82,
  true,
  jsonb_build_object(
    'seed_batch', 'crm_targeted_small_agencies_2026-03-04',
    'active_listings_count', s.active_listings_count,
    'share_kauf_percent', s.share_kauf_percent,
    'share_miete_percent', s.share_miete_percent
  )
from upserted u
join seed s
  on s.company_name = u.company_name
 and s.city = u.city
where not exists (
  select 1
  from public.crm_research_notes n
  where n.prospect_id = u.id
    and n.agent_id = u.agent_id
    and coalesce(n.source_url, '') = coalesce(s.source_url, '')
);

commit;
